#!/usr/bin/env bash

source ./cmd.config

echo ""
echo ""
echo "CONFIGURING SQITCH ENGINE"
echo ""

for i in ${packages[@]};
do
  echo "CONFIGURING PACKAGE ------------------------------------------------------------" $i
  (cd ./"$i"/ && sqitch engine add pg "$database")
done
