#!/usr/bin/env bash

source ./cmd.config

echo ""
echo ""
echo "REVERTING"
echo ""


for (( idx=${#packages[@]}-1 ; idx>=0 ; idx-- )) ; do
  echo "REVERTING PACKAGE ------------------------------------------------------------" ${packages[idx]}
  (cd ./release/ && sqitch revert --target ${packages[idx]} -y)
done
