#!/usr/bin/env bash

source ./cmd.config

echo ""
echo ""
echo "CONFIGURING SQITCH TARGET"
echo ""

for i in ${packages[@]};
do
  echo "CONFIGURING PACKAGE ------------------------------------------------------------" $i
  (cd ./release/"$i"/ && sqitch target add "$database" db:pg:"$database")
done
