- hosts: localhost
  connection: local
  vars_files: 
    - ../config.yml
  tasks:
    - import_tasks: ./tasks/create-environment-resources.yml
      vars:
        env: "{{ env }}"
        git_branch: "{{ git_branch }}"
        # deployment_slot: "{{ deployment_slot }}"
