- name: create devops project for {{ project_name }}
  shell: >
    az devops project create 
    --name "{{ project_name }}"
    --organization "{{ organization_url }}"

- name: create api repo for {{ project_name }}
  shell: >
    az repos create 
    --name "api"
    --project "{{ project_name }}"
    --organization "{{ organization_url }}"

- name: create db repo for {{ project_name }}
  shell: >
    az repos create 
    --name "db"
    --project "{{ project_name }}"
    --organization "{{ organization_url }}"

- name: create web-vue repo for {{ project_name }}
  shell: >
    az repos create 
    --name "web-vue"
    --project "{{ project_name }}"
    --organization "{{ organization_url }}"

- name: create az-config repo for {{ project_name }}
  shell: >
    az repos create 
    --name "az-config"
    --project "{{ project_name }}"
    --organization "{{ organization_url }}"

- name: create cli repo for {{ project_name }}
  shell: >
    az repos create 
    --name "cli"
    --project "{{ project_name }}"
    --organization "{{ organization_url }}"

- name: get the default repo
  shell: >
    az repos show
    --organization "{{ organization_url }}"
    --project "{{ project_name }}"
    --repository "{{ project_name }}"
  register: default_repo_result

- name: parse default repo
  set_fact: 
    default_repo: "{{ default_repo_result.stdout | from_json }}"

- debug: var=default_repo

- name: delete default repo for {{ project_name }}
  shell: >
    az repos delete
    --id "{{ default_repo.id }}"
    --project "{{ project_name }}"
    --organization "{{ organization_url }}"
    --yes
