# api-{{ env }}
- name: delete {{ env }} api resource group
  shell: >
    az group delete 
    --name "{{ resource_group_name_base }}-api-{{ env }}"
    --yes

# db-{{ env }}
- name: delete {{ env }} db resource group
  shell: >
    az group delete 
    --name "{{ resource_group_name_base }}-db-{{ env }}"
    --yes

