# app_name: ps-demo
# location: westus2
# storage_account_name: psdemosa
# storage_share_name_base: web-dist
# db_admin_user_name: psdemoadmin
# db_admin_user_password: b@Dpa$SW0rdb@Dpa$SW0rd
# db_name: phile_starter

resource_group_name_base: ps-demo-rg
# traffic_manager_profile_name: ps-demo-tm-profile
# traffic_manager_endpoint_name: ps-demo-tm-endpoint
appservice_plan_name_base: ps-demo-asp
container_registry_name: psdemocr
docker_image_name: phile-starter-api
location: westus2
storage_account_name: psdemosa
storage_share_name_base: web-dist
appservice_name: ps-demo
db_admin_user_name: psdemoadmin
db_admin_user_password: LL38f7ooLL38f7oo
db_name: phile_starter