
module.exports = {
  apps : [
    {
      name: "leaf-fractal",
      script: "./src/leaf/syncServer/server.js",
      exec_mode: "cluster",
      instances: 1,
      ignore_watch: ["node_modules", "logs"],
      autorestart: false,
      env: {
        LEAF_MME_NAME: 'FRACTAL',
        LEAF_MME_CODE: 'M417364',
        LEAF_BASE_API: 'https://traceability.lcb.wa.gov/api/v1',
        SORO_QUOTING_API_ENDPOINT: 'https://dev-wa.soro.biz/graphql',
        SORO_AUTH: true,
        SORO_USERNAME: 'kevinpp',
        SORO_PASSWORD: 'soro$Secret',
        POLLING_INTERVAL: (1000 * 60 * 60)
      },
    },
    // {
    //   name: "leaf-stryps",
    //   script: "./src/leaf/syncServer/server.js",
    //   exec_mode: "cluster",
    //   instances: 1,
    //   ignore_watch: ["node_modules", "logs"],
    //   autorestart: false,
    //   env_dev: {
    //     LEAF_MME_NAME: 'STRYPS',
    //     LEAF_MME_CODE: 'M417285',
    //     LEAF_BASE_API: 'https://traceability.lcb.wa.gov/api/v1',
    //     SORO_QUOTING_API_ENDPOINT: 'https://dev-wa.soro.biz/graphql',
    //     SORO_AUTH: true,
    //     SORO_USERNAME: 'kevinpp',
    //     SORO_PASSWORD: 'soro$Secret',
    //     POLLING_INTERVAL: (1000 * 60 * 60)
    //   },
    // },
    // {
    //   name: "leaf-egherb",
    //   script: "./src/leaf/syncServer/server.js",
    //   exec_mode: "cluster",
    //   instances: 1,
    //   ignore_watch: ["node_modules", "logs"],
    //   autorestart: false,
    //   env_dev: {
    //     LEAF_MME_NAME: 'EVERGREEN HERBAL',
    //     LEAF_MME_CODE: 'M078256',
    //     LEAF_BASE_API: 'https://traceability.lcb.wa.gov/api/v1',
    //     SORO_QUOTING_API_ENDPOINT: 'https://dev-wa.soro.biz/graphql',
    //     SORO_AUTH: true,
    //     SORO_USERNAME: 'kevinpp',
    //     SORO_PASSWORD: 'soro$Secret',
    //     POLLING_INTERVAL: (1000 * 60 * 60)
    //   },
    // },
    // {
    //   name: "leaf-epeaks",
    //   script: "./src/leaf/syncServer/server.js",
    //   exec_mode: "cluster",
    //   instances: 1,
    //   ignore_watch: ["node_modules", "logs"],
    //   autorestart: false,
    //   env_dev: {
    //     LEAF_MME_NAME: 'EMERALD PEAKS',
    //     LEAF_MME_CODE: 'M416198',
    //     LEAF_BASE_API: 'https://traceability.lcb.wa.gov/api/v1',
    //     SORO_QUOTING_API_ENDPOINT: 'https://dev-wa.soro.biz/graphql',
    //     SORO_AUTH: true,
    //     SORO_USERNAME: 'kevinpp',
    //     SORO_PASSWORD: 'soro$Secret',
    //     POLLING_INTERVAL: (1000 * 60 * 60)
    //   },
    // },
    // {
    //   name: "leaf-pur",
    //   script: "./src/leaf/syncServer/server.js",
    //   exec_mode: "cluster",
    //   instances: 1,
    //   ignore_watch: ["node_modules", "logs"],
    //   autorestart: false,
    //   env_dev: {
    //     LEAF_MME_NAME: 'QUALITY GROWERS',
    //     LEAF_MME_CODE: 'J417338',
    //     LEAF_BASE_API: 'https://traceability.lcb.wa.gov/api/v1',
    //     SORO_QUOTING_API_ENDPOINT: 'https://dev-wa.soro.biz/graphql',
    //     SORO_AUTH: true,
    //     SORO_USERNAME: 'kevinpp',
    //     SORO_PASSWORD: 'soro$Secret',
    //     POLLING_INTERVAL: (1000 * 60 * 60)
    //   },
    // },
    // {
    //   name: "leaf-hannah",
    //   script: "./src/leaf/syncServer/server.js",
    //   exec_mode: "cluster",
    //   instances: 1,
    //   ignore_watch: ["node_modules", "logs"],
    //   autorestart: false,
    //   env_dev: {
    //     LEAF_MME_NAME: 'HANNAH INDUSTRIES',
    //     LEAF_MME_CODE: 'J424223',
    //     LEAF_BASE_API: 'https://traceability.lcb.wa.gov/api/v1',
    //     SORO_QUOTING_API_ENDPOINT: 'https://dev-wa.soro.biz/graphql',
    //     SORO_AUTH: true,
    //     SORO_USERNAME: 'kevinpp',
    //     SORO_PASSWORD: 'soro$Secret',
    //     POLLING_INTERVAL: (1000 * 60 * 60)
    //   },
    // },
    // {
    //   name: "leaf-gold",
    //   script: "./src/leaf/syncServer/server.js",
    //   exec_mode: "cluster",
    //   instances: 1,
    //   ignore_watch: ["node_modules", "logs"],
    //   autorestart: false,
    //   env_dev: {
    //     LEAF_MME_NAME: 'CAVIAR GOLD',
    //     LEAF_MME_CODE: 'M412861',
    //     LEAF_BASE_API: 'https://traceability.lcb.wa.gov/api/v1',
    //     SORO_QUOTING_API_ENDPOINT: 'https://dev-wa.soro.biz/graphql',
    //     SORO_AUTH: true,
    //     SORO_USERNAME: 'kevinpp',
    //     SORO_PASSWORD: 'soro$Secret',
    //     POLLING_INTERVAL: (1000 * 60 * 60)
    //   },
    // },
    // {
    //   name: "leaf-heylo",
    //   script: "./src/leaf/syncServer/server.js",
    //   exec_mode: "cluster",
    //   instances: 1,
    //   ignore_watch: ["node_modules", "logs"],
    //   autorestart: false,
    //   env_dev: {
    //     LEAF_MME_NAME: 'HEYLO',
    //     LEAF_MME_CODE: 'M417288',
    //     LEAF_BASE_API: 'https://traceability.lcb.wa.gov/api/v1',
    //     SORO_QUOTING_API_ENDPOINT: 'https://dev-wa.soro.biz/graphql',
    //     SORO_AUTH: true,
    //     SORO_USERNAME: 'kevinpp',
    //     SORO_PASSWORD: 'soro$Secret',
    //     POLLING_INTERVAL: (1000 * 60 * 60)
    //   },
    // },
    // {
    //   name: "leaf-stickybudz",
    //   script: "./src/leaf/syncServer/server.js",
    //   exec_mode: "cluster",
    //   instances: 1,
    //   ignore_watch: ["node_modules", "logs"],
    //   autorestart: false,
    //   env_dev: {
    //     LEAF_MME_NAME: 'STICKY BUDZ',
    //     LEAF_MME_CODE: 'J412076',
    //     LEAF_BASE_API: 'https://traceability.lcb.wa.gov/api/v1',
    //     SORO_QUOTING_API_ENDPOINT: 'https://dev-wa.soro.biz/graphql',
    //     SORO_AUTH: true,
    //     SORO_USERNAME: 'kevinpp',
    //     SORO_PASSWORD: 'soro$Secret',
    //     POLLING_INTERVAL: (1000 * 60 * 60)
    //   },
    // },
    // {
    //   name: "leaf-mfused",
    //   script: "./src/leaf/syncServer/server.js",
    //   exec_mode: "cluster",
    //   instances: 1,
    //   ignore_watch: ["node_modules", "logs"],
    //   autorestart: false,
    //   env_dev: {
    //     LEAF_MME_NAME: 'MFUSED',
    //     LEAF_MME_CODE: 'M415766',
    //     LEAF_BASE_API: 'https://traceability.lcb.wa.gov/api/v1',
    //     SORO_QUOTING_API_ENDPOINT: 'https://dev-wa.soro.biz/graphql',
    //     SORO_AUTH: true,
    //     SORO_USERNAME: 'kevinpp',
    //     SORO_PASSWORD: 'soro$Secret',
    //     POLLING_INTERVAL: (1000 * 60 * 60)
    //   },
    // },
    // {
    //   name: "leaf-wow",
    //   script: "./src/leaf/syncServer/server.js",
    //   exec_mode: "cluster",
    //   instances: 1,
    //   ignore_watch: ["node_modules", "logs"],
    //   autorestart: false,
    //   env_dev: {
    //     LEAF_MME_NAME: 'W.O.W. INDUSTRIES',
    //     LEAF_MME_CODE: 'J413922',
    //     LEAF_BASE_API: 'https://traceability.lcb.wa.gov/api/v1',
    //     SORO_QUOTING_API_ENDPOINT: 'https://dev-wa.soro.biz/graphql',
    //     SORO_AUTH: true,
    //     SORO_USERNAME: 'kevinpp',
    //     SORO_PASSWORD: 'soro$Secret',
    //     POLLING_INTERVAL: (1000 * 60 * 60)
    //   },
    // },
  ]
}
