process.env.PORT = 8080
process.env.DB_CONNECTION_STRING = 'postgres://USER:PASSWORD@HOST/DATABASE'
process.env.SCHEMAS_TO_GRAPHQL = ['soro', 'biotrack']
process.env.PG_DEFAULT_ROLE = 'soro_anonymous'
process.env.GRAPHIQL = false
process.env.JWT_PG_TYPE_IDENTIFIER = 'soro.jwt_token'
process.env.JWT_SECRET = 'S*PERDuPER$#(R#T'
process.env.DISABLE_DEFAULT_MUTATIONS = true
process.env.CONFIRM_QUOTE_URL_BASE = 'SERVER_URL/#/confirm-quote/'
process.env.MAILGUN_API_KEY = 'MAILGUN_API_KEY'
process.env.MAILGUN_DOMAIN = 'mg.soro.biz'