# THESE ARE THE ONLY VARIABLES THAT SHOULD NEED TO CHANGE
organization_user: stlbucket
organization_name: stlbucket
project_name: tunz
project_name_no_caps: tunz
db_name: tunz
location: westus2
db_admin_user_password: LL38f7ooLL38f7oo
# THOSE WERE THE ONLY VARIABLES THAT SHOULD NEED TO CHANGE
s

organization_url: https://dev.azure.com/{{organization_name}}
resource_group_name_base: {{project_name}}-rg
appservice_plan_name_base: {{project_name}}-asp
container_registry_name: {{project_name_no_caps}}cr
docker_image_name: {{project_name}}-api
storage_account_name: {{project_name_no_caps}}sa
storage_share_name_base: web-dist
appservice_name: {{project_name}}
db_admin_user_name: {{project_name_no_caps}}admin
# traffic_manager_profile_name: tunz-tm-profile
# traffic_manager_endpoint_name: tunz-tm-endpoint
