- hosts: localhost
  connection: local
  vars_files: 
    - ./config.yml
  tasks:
    - import_tasks: ./tasks/create-devops-project-and-repos.yml

    - name: create azure-pipelines.yml file for api repo
      template:
        src: templates/api-azure-pipelines.yml.j2
        dest: ../api/azure-pipelines.yml

    - name: create azure-pipelines.yml file for web-vue repo
      template:
        src: templates/web-vue-azure-pipelines.yml.j2
        dest: ../web-vue/azure-pipelines.yml

    - import_tasks: ./tasks/initialize-devops-git-repo.yml
      vars:
        repo_name: api

    - import_tasks: ./tasks/initialize-devops-git-repo.yml
      vars:
        repo_name: db

    - import_tasks: ./tasks/initialize-devops-git-repo.yml
      vars:
        repo_name: web-vue

    - import_tasks: ./tasks/initialize-devops-git-repo.yml
      vars:
        repo_name: cli

    - import_tasks: ./tasks/initialize-devops-git-repo.yml
      vars:
        repo_name: az-config

